#ifndef PSX_XG_RENDER_AUTH_HOOK_TYPES_H
#define PSX_XG_RENDER_AUTH_HOOK_TYPES_H

typedef enum PsxXgRenderAuthHook {
    PSX_XG_RENDER_AUTH_HOOK_PRODUCER_ENTRY = 0,
    PSX_XG_RENDER_AUTH_HOOK_INTERNAL_OBSERVATION = 1,
    PSX_XG_RENDER_AUTH_HOOK_CONTINUATION = 2,
    PSX_XG_RENDER_AUTH_HOOK_PRODUCER_EXIT = 3,
    PSX_XG_RENDER_AUTH_HOOK_FOREIGN_INTERIOR = 4,
    PSX_XG_RENDER_AUTH_HOOK_SOURCE_PRE = 5,
    PSX_XG_RENDER_AUTH_HOOK_SOURCE_COMMIT = 6,
    PSX_XG_RENDER_AUTH_HOOK_ENTRY = PSX_XG_RENDER_AUTH_HOOK_PRODUCER_ENTRY,
    PSX_XG_RENDER_AUTH_HOOK_CAPTURE =
        PSX_XG_RENDER_AUTH_HOOK_INTERNAL_OBSERVATION,
    PSX_XG_RENDER_AUTH_HOOK_RETURN = PSX_XG_RENDER_AUTH_HOOK_CONTINUATION,
} PsxXgRenderAuthHook;

#endif
