set(PSXRECOMP_RUNTIME_BIOS_ONLY_GAME_IDENTITY_DOMAIN "psxrecomp-runtime:bios-only:game-identity:v1")
set(PSXRECOMP_RUNTIME_BIOS_ONLY_MANIFEST_IDENTITY_DOMAIN "psxrecomp-runtime:bios-only:manifest-identity:v1")
string(SHA256 PSXRECOMP_RUNTIME_BIOS_ONLY_GAME_IDENTITY_SHA256
    "${PSXRECOMP_RUNTIME_BIOS_ONLY_GAME_IDENTITY_DOMAIN}")
string(SHA256 PSXRECOMP_RUNTIME_BIOS_ONLY_MANIFEST_IDENTITY_SHA256
    "${PSXRECOMP_RUNTIME_BIOS_ONLY_MANIFEST_IDENTITY_DOMAIN}")
if(PSXRECOMP_RUNTIME_BIOS_ONLY_GAME_IDENTITY_SHA256 STREQUAL
   PSXRECOMP_RUNTIME_BIOS_ONLY_MANIFEST_IDENTITY_SHA256)
    message(FATAL_ERROR "psx-runtime BIOS-only identities must stay distinct")
endif()

psxrecomp_add_runtime_target(psx-runtime
    DEBUG_PORT 4370
    WINDOW_TITLE "psxrecomp - BIOS"
    DEFAULT_BIOS_PATH "${PSXRECOMP_ROOT}/bios/SCPH1001.BIN"
    EXE_NAME "PSXRecomp"
    GAME_EXTRA_IDENTITY_SHA256 "${PSXRECOMP_RUNTIME_BIOS_ONLY_GAME_IDENTITY_SHA256}"
    GAME_MANIFEST_DIGEST_SHA256 "${PSXRECOMP_RUNTIME_BIOS_ONLY_MANIFEST_IDENTITY_SHA256}"
)

if(BUILD_TESTING)
    add_test(NAME runtime_identity_caller_test
             COMMAND ${CMAKE_COMMAND}
                     -DPSXRECOMP_ROOT=${PSXRECOMP_ROOT}
                     -P ${CMAKE_CURRENT_LIST_DIR}/tests/check_runtime_identity_caller.cmake)
endif()

if(NOT MSVC)
    psxrecomp_add_runtime_target(psx-oracle
        ORACLE
        DEBUG_PORT 4371
        WINDOW_TITLE "psxrecomp - Oracle"
        DEFAULT_BIOS_PATH "${PSXRECOMP_ROOT}/bios/SCPH1001.BIN"
        GAME_EXTRA_IDENTITY_SHA256 "${PSXRECOMP_RUNTIME_BIOS_ONLY_GAME_IDENTITY_SHA256}"
        GAME_MANIFEST_DIGEST_SHA256 "${PSXRECOMP_RUNTIME_BIOS_ONLY_MANIFEST_IDENTITY_SHA256}"
    )
endif()
